"""initial models

Revision ID: 09f8748543a0
Revises: 
Create Date: 2026-02-18 12:39:39.068924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f8748543a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('borough', sa.String(length=50), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('service_zone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=False),
    sa.Column('dropoff_datetime', sa.DateTime(), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('trip_distance', sa.Float(), nullable=True),
    sa.Column('ratecode_id', sa.Integer(), nullable=True),
    sa.Column('store_and_fwd_flag', sa.String(length=1), nullable=True),
    sa.Column('pulocation_id', sa.Integer(), nullable=True),
    sa.Column('dolocation_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Integer(), nullable=True),
    sa.Column('fare_amount', sa.Float(), nullable=True),
    sa.Column('extra', sa.Float(), nullable=True),
    sa.Column('mta_tax', sa.Float(), nullable=True),
    sa.Column('tip_amount', sa.Float(), nullable=True),
    sa.Column('tolls_amount', sa.Float(), nullable=True),
    sa.Column('improvement_surcharge', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('congestion_surcharge', sa.Float(), nullable=True),
    sa.Column('trip_duration_minutes', sa.Float(), nullable=True),
    sa.Column('trip_speed_mph', sa.Float(), nullable=True),
    sa.Column('fare_per_mile', sa.Float(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('time_of_day_category', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dolocation_id'], ['zones.location_id'], ),
    sa.ForeignKeyConstraint(['pulocation_id'], ['zones.location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index('idx_dolocation', ['dolocation_id'], unique=False)
        batch_op.create_index('idx_pickup_datetime', ['pickup_datetime'], unique=False)
        batch_op.create_index('idx_pulocation', ['pulocation_id'], unique=False)
        batch_op.create_index('idx_vendor', ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index('idx_vendor')
        batch_op.drop_index('idx_pulocation')
        batch_op.drop_index('idx_pickup_datetime')
        batch_op.drop_index('idx_dolocation')

    op.drop_table('trips')
    op.drop_table('zones')
    # ### end Alembic commands ###
